# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

#/var/lib/docker/volumes
#本地与远程服务器主机形成映射
volumes:
  orderer.test.com:
  couchdb01:
  peer0.org01.test.com:
  ca.org01.com:

networks:
  byfn:

services:

  couchdb01:
    container_name: couchdb01
    image: hyperledger/fabric-couchdb:latest
    # Populate the COUCHDB_USER and COUCHDB_PASSWORD to set an admin user and password
    # for CouchDB.  This will prevent CouchDB from operating in an "Admin Party" mode.
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=123456
    # Comment/Uncomment the port mapping if you want to hide/expose the CouchDB service,
    # for example map it to utilize Fauxton User Interface in dev environments.
    ports:
      - "5984:5984"
    networks:
      - byfn

  ca.org01.com:
    image: hyperledger/fabric-ca:latest
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.org01.com
      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.org01.test.com-cert.pem
      - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/6440e4a3b1f247fa1f9a99a85d1249c349c0634ca57dc0e0c4922fcd8f0cd38d_sk
    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start -b admin:123'
    volumes:
      - ./crypto-config/peerOrganizations/org01.test.com/ca:/etc/hyperledger/fabric-ca-server-config
    container_name: ca.org01.com
    networks:
      - byfn
      
  orderer.test.com:
    extends:
      file:   base/docker-compose-base.yaml
      service: orderer.test.com
    container_name: orderer.test.com
    networks:
      - byfn

  peer0.org01.test.com:
    container_name: peer0.org01.test.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.org01.test.com
    depends_on:
      - couchdb01   
    networks:
      - byfn

  cli:
    container_name: cli
    image: hyperledger/fabric-tools:latest
    tty: true
    stdin_open: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      #- CORE_LOGGING_LEVEL=DEBUG
      - CORE_LOGGING_LEVEL=INFO
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.org01.test.com:7051
      - CORE_PEER_LOCALMSPID=Org01MSP
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org01.test.com/peers/peer0.org01.test.com/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org01.test.com/peers/peer0.org01.test.com/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org01.test.com/peers/peer0.org01.test.com/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org01.test.com/users/Admin@org01.test.com/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
        - /var/run/:/host/var/run/
        - ./chaincode/:/opt/gopath/src/github.com/chaincode
        - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
        - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
    depends_on:
      - orderer.test.com
      - couchdb01
      - peer0.org01.test.com
      - ca.org01.com
    networks:
      - byfn
