# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

services:

  orderer.test.com:
    container_name: orderer.test.com
    image: hyperledger/fabric-orderer:latest
    environment:
      - ORDERER_GENERAL_LOGLEVEL=INFO
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/orderer.genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      # enabled TLS
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      #- ORDERER_GENERAL_TLS_ROOTCAS=/var/hyperledger/orderer/tls/ca.crt
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    volumes:
    - ../channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
    - ../crypto-config/ordererOrganizations/test.com/orderers/orderer.test.com/msp:/var/hyperledger/orderer/msp
    - ../crypto-config/ordererOrganizations/test.com/orderers/orderer.test.com/tls/:/var/hyperledger/orderer/tls
    - orderer.test.com:/var/hyperledger/production/orderer
    ports:
      - 7050:7050

  peer0.orggo.test.com:
    container_name: peer0.orggo.test.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.orggo.test.com
      - CORE_PEER_ADDRESS=peer0.orggo.test.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.orggo.test.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.orggo.test.com:7051
      - CORE_PEER_LOCALMSPID=OrgGoMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/orggo.test.com/peers/peer0.orggo.test.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/orggo.test.com/peers/peer0.orggo.test.com/tls:/etc/hyperledger/fabric/tls
        - peer0.orggo.test.com:/var/hyperledger/production
    ports:
      - 7051:7051
      #command: peer node start --peer-chaincodedev=true 配合7052调试端口
      #- 7052:7052 
      - 7053:7053

  peer1.orggo.test.com:
    container_name: peer1.orggo.test.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.orggo.test.com
      - CORE_PEER_ADDRESS=peer1.orggo.test.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.orggo.test.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.orggo.test.com:7051
      - CORE_PEER_LOCALMSPID=OrgGoMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/orggo.test.com/peers/peer1.orggo.test.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/orggo.test.com/peers/peer1.orggo.test.com/tls:/etc/hyperledger/fabric/tls
        - peer1.orggo.test.com:/var/hyperledger/production

    ports:
      - 8051:7051
      #command: peer node start --peer-chaincodedev=true 配合7052调试端口
      #- 7052:7052 
      - 8053:7053

  peer0.orgcpp.test.com:
    container_name: peer0.orgcpp.test.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.orgcpp.test.com
      - CORE_PEER_ADDRESS=peer0.orgcpp.test.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.orgcpp.test.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.orgcpp.test.com:7051
      - CORE_PEER_LOCALMSPID=OrgCppMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/orgcpp.test.com/peers/peer0.orgcpp.test.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/orgcpp.test.com/peers/peer0.orgcpp.test.com/tls:/etc/hyperledger/fabric/tls
        - peer0.orgcpp.test.com:/var/hyperledger/production
    ports:
      - 9051:7051
      #command: peer node start --peer-chaincodedev=true 配合7052调试端口
      #- 7052:7052 
      - 9053:7053

  peer1.orgcpp.test.com:
    container_name: peer1.orgcpp.test.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.orgcpp.test.com
      - CORE_PEER_ADDRESS=peer1.orgcpp.test.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.orgcpp.test.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.orgcpp.test.com:7051
      - CORE_PEER_LOCALMSPID=OrgCppMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/orgcpp.test.com/peers/peer1.orgcpp.test.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/orgcpp.test.com/peers/peer1.orgcpp.test.com/tls:/etc/hyperledger/fabric/tls
        - peer1.orgcpp.test.com:/var/hyperledger/production
    ports:
      - 10051:7051
      #command: peer node start --peer-chaincodedev=true 配合7052调试端口
      #- 7052:7052 
      - 10053:7053
