# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

#/var/lib/docker/volumes
#本地与远程服务器主机形成映射
volumes:
  orderer.test.com:
  peer0.orggo.test.com:
  peer1.orggo.test.com:
  peer0.orgcpp.test.com:
  peer1.orgcpp.test.com:

networks:
  byfn:

services:

  orderer.test.com:
    extends:
      file:   base/docker-compose-base.yaml
      service: orderer.test.com
    container_name: orderer.test.com
    networks:
      - byfn

  peer0.orggo.test.com:
    container_name: peer0.orggo.test.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.orggo.test.com
    networks:
      - byfn

  peer1.orggo.test.com:
    container_name: peer1.orggo.test.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.orggo.test.com
    networks:
      - byfn

  peer0.orgcpp.test.com:
    container_name: peer0.orgcpp.test.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.orgcpp.test.com
    networks:
      - byfn

  peer1.orgcpp.test.com:
    container_name: peer1.orgcpp.test.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.orgcpp.test.com
    networks:
      - byfn

  cli:
    container_name: cli
    image: hyperledger/fabric-tools:latest
    tty: true
    stdin_open: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      #- CORE_LOGGING_LEVEL=DEBUG
      - CORE_LOGGING_LEVEL=INFO
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.orggo.test.com:7051
      - CORE_PEER_LOCALMSPID=OrgGoMSP
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/orggo.test.com/peers/peer0.orggo.test.com/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/orggo.test.com/peers/peer0.orggo.test.com/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/orggo.test.com/peers/peer0.orggo.test.com/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/orggo.test.com/users/Admin@orggo.test.com/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
        - /var/run/:/host/var/run/
        - ./chaincode/:/opt/gopath/src/github.com/chaincode
        - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
        - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
    depends_on:
      - orderer.test.com
      - peer0.orggo.test.com
      - peer1.orggo.test.com
      - peer0.orgcpp.test.com
      - peer1.orgcpp.test.com
    networks:
      - byfn
