
# ---------------------------------------------------------------------------
# "OrdererOrgs" - Definition of organizations managing orderer nodes
# ---------------------------------------------------------------------------
OrdererOrgs:
  # ---------------------------------------------------------------------------
  # Orderer
  # ---------------------------------------------------------------------------
  - Name: Orderer
    Domain: test.com
    Specs:
      - Hostname: orderer

PeerOrgs:
  - Name: Org01
    Domain: org01.test.com
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1
